### ISSUE TITLE
'CameraControl' object has no attribute 'camera_ptz'

### ISSUE THREAD

**Issue by kindofausername** [smartsenselab/sensecam-control#10]
Hello PTZ-Fans,

I tried running your package example code but run into following error:

Python 3.9.7 | packaged by conda-forge | (default, Sep 29 2021, 20:33:18) 
[Clang 11.1.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> IP = "192.168.178.52"  # Camera IP address
>>> 
>>> PORT = 8080  # Port
>>> USER = "admin"  # Username
>>> PASS = "admin"  # Password
>>> from sensecam_control import onvif_control
>>> Camera2 = onvif_control.CameraControl(IP, USER, PASS)
>>> Camera2.absolute_move(0.02, 0.60, 0.0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mymac/anaconda3/envs/onvif39/lib/python3.9/site-packages/sensecam_control/onvif_control.py", line 64, in absolute_move
    request = self.camera_ptz.create_type('AbsoluteMove')
AttributeError: 'CameraControl' object has no attribute 'camera_ptz'

Any idea how to get my cam working?

Greetings,
Armin

**Comment by wiseman** [comment]
I ran into this same issue. I notice that the onvif control example only uses `relative_move`, not `absolute_move`.

**Comment by wiseman** [comment]
Oh, I think you need to call `camera_start()` before calling a move method.
