### ISSUE TITLE
onvif.exceptions.ONVIFError: Unknown error: Unknown fault occured

### ISSUE THREAD

**Issue by prashant36** [smartsenselab/sensecam-control#6]
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\onvif\client.py", line 23, in wrapped
    return func(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\onvif\client.py", line 153, in wrapped
    return call(params, callback)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\onvif\client.py", line 140, in call
    ret = func(**params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\zeep\proxy.py", line 46, in __call__
    return self._proxy._binding.send(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\zeep\wsdl\bindings\soap.py", line 135, in send
    return self.process_reply(client, operation_obj, response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\zeep\wsdl\bindings\soap.py", line 229, in process_reply
    return self.process_error(doc, operation)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\zeep\wsdl\bindings\soap.py", line 352, in process_error
    raise Fault(
zeep.exceptions.Fault: Unknown fault occured

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\prashant\ptz_test\test2.py", line 63, in <module>
    X.camera_start()
  File "C:\Users\Administrator\Downloads\prashant\ptz_test\sensecam_control\onvif_control.py", line 36, in camera_start
    mycam = ONVIFCamera(self.__cam_ip, 80, self.__cam_user, self.__cam_password)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\onvif\client.py", line 216, in __init__
    self.update_xaddrs()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\onvif\client.py", line 233, in update_xaddrs
    capabilities = self.devicemgmt.GetCapabilities({'Category': 'All'})
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\onvif\client.py", line 26, in wrapped
    raise ONVIFError(err)
onvif.exceptions.ONVIFError: Unknown error: Unknown fault occured

**Comment by Biaocsu** [comment]
@prashant36 Hi, I met this problem too, could you tell me how do you solve it ? thank you
